### ISSUE TITLE
javadoc: error - invalid flag: -d

### ISSUE THREAD

**Issue by priyeshshah11** [manoelcampos/javadoc-coverage#13]
Tried using javadoc-coverage with gradle as per the steps in the README.
Get the following error : `javadoc: error - invalid flag: -d`

_Note: Running javdaoc without the coverage doclet works fine._ 

Is this a known issue? Couldn't find much support elsewhere.

**Comment by yixqiao** [comment]
I'm having the exact same problem.
Javadoc is also giving this warning:
`javadoc: warning - The old Doclet and Taglet APIs in the packages
com.sun.javadoc, com.sun.tools.doclets and their implementations
are planned to be removed in a future JDK release. These
components have been superseded by the new APIs in jdk.javadoc.doclet.
Users are strongly recommended to migrate to the new APIs.`

EDIT: it might be due to using Java 9 ([see this issue](https://github.com/manoelcampos/javadoc-coverage/issues/12)).

**Comment by priyeshshah11** [comment]
> I'm having the exact same problem.
> Javadoc is also giving this warning:
> `javadoc: warning - The old Doclet and Taglet APIs in the packages com.sun.javadoc, com.sun.tools.doclets and their implementations are planned to be removed in a future JDK release. These components have been superseded by the new APIs in jdk.javadoc.doclet. Users are strongly recommended to migrate to the new APIs.`
> 
> EDIT: it might be due to using Java 9 ([see this issue](https://github.com/manoelcampos/javadoc-coverage/issues/12)).

I am using Java 11.

**Comment by yixqiao** [comment]
I got javadoc-coverage to work by using it within a Java 8 environment (I also usually use Java 11).
I happened to have a conda environment with Java 8, so I ran it within the environment, and everything worked as expected.
A better idea for using Java 8 would probably be using sdkman as described [here](https://github.com/manoelcampos/javadoc-coverage/issues/12#issuecomment-457857304).

**Comment by manoelcampos** [comment]
Hello guys, sorry for the late reply, but I'm been very busy these days.
This is an issue with newer JDK versions.
Check #12 for details.
Unfortunately, I do not have time to make the changes to support JDK9+.
