### ISSUE TITLE
Overridden Interface/Abstract Methods potentially don't need separate Documentation

### ISSUE THREAD

**Issue by stieglma** [manoelcampos/javadoc-coverage#9]
For interface methods it is clear that they should be documented in the interface itself and not in the implementing classes (no duplicate documentation necessary!)

For methods overridden from super classes this might as well be the case, however behavior could be different in them, so there is potentially the need for additional documentation.

In general, I would ignore the second case, and count them separately, but all interface methods shouldn't be counted in the implementing classes.

**Comment by manoelcampos** [comment]
Thanks for the contribution @stieglma.
I've just closed this issue. See the commit message for more details.
You can run `mvn package` on the sample project and check the information for the class `SubClass1` in the JavaDoc Coverage Report. The class has some overridden methods: 

- one with no documentation at all, which is counted as completed documented, since the superclass is accountable for its documentation;
- other ones with partial documentation, which are computed as usual.

**Comment by stieglma** [comment]
very cool! thanks for the fast response and implementation! My merge request with the "coverage for public stuff only" will hopefully come sometime today
